### ISSUE TITLE
Enhancement - allow setting concurrency

### ISSUE THREAD

**Issue by scotwk** [nficano/python-lambda#103]
Looks like setting the concurrency isn't allowed in `create_function` or `update_function_configuration`

This would require callouts to two separate functions:

[put_function_concurrency](http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.put_function_concurrency)

[delete_function_concurrency](http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.delete_function_concurrency)

**Comment by soapergem** [comment]
These changes have been incorporated into the latest release (3.2.6).

To use them simply add something like this to your `config.yaml` file:

```
concurrency: 600
```
