### ISSUE TITLE
Add support for injecting environment variables

### ISSUE THREAD

**Issue by loren** [nficano/python-lambda#11]
I'm not sure if there's a way to do this already with python-lambda, but the node-lambda library handles it this way: https://github.com/motdotla/node-lambda#custom-environment-variables

**Comment by quiqua** [comment]
You can also just use [git secret](https://github.com/sobolevn/git-secret) to  add an encrypted file to the repository.
With each deploy, the decrypted files gets uploaded as well.

**Comment by jmeekhof** [comment]
feature added and merged to master.
