### ISSUE TITLE
AWS LAMBDA - Unable to import module

### ISSUE THREAD

**Issue by RazvanTolbaru** [nficano/python-lambda#118]
Hi, 

I've followed the **Getting Started** guide. 

Folder structure:
```bash
→  ll
total 24
drwxr-xr-x  3 razvan.tolbaru  staff   102B Jul 25 15:05 __pycache__/
-rw-r--r--  1 razvan.tolbaru  staff   1.1K Jul 25 15:01 config.yaml
drwxr-xr-x  3 razvan.tolbaru  staff   102B Jul 25 15:01 dist/
-rw-r--r--  1 razvan.tolbaru  staff    31B Jul 25 14:59 event.json
-rw-r--r--  1 razvan.tolbaru  staff   163B Jul 25 15:01 service.py
drwxr-xr-x  7 razvan.tolbaru  staff   238B Jul 25 14:14 venv/
```
This is my **service.py**:
```python
# -*- coding: utf-8 -*-

import OpenSSL

def handler(event, context):
    # Your code goes here!
    e = event.get('e')
    pi = event.get('pi')
    return e + pi
```

Invoking the lambda function locally works without any issues.
```bash
→lambda invoke
5.8580000000000005
```
Deployed to AWS without any errors:
```bash
→ lambda deploy
Gathering pip packages
Installing asn1crypto==0.24.0
Installing boto3==1.4.4
Installing botocore==1.5.62
Installing cffi==1.11.5
Installing click==6.6
Installing cryptography==2.3
Installing docutils==0.12
Installing futures==3.1.1
Installing idna==2.7
Installing jmespath==0.9.0
Installing pip==18.0
Installing pyaml==15.8.2
Installing pycparser==2.18
Installing pyOpenSSL==18.0.0
Installing python-dateutil==2.5.3
Installing PyYAML==3.11
Installing s3transfer==0.1.13
Installing setuptools==40.0.0
Installing six==1.10.0
Installing wheel==0.31.1
Bundling: 'service.py'
Bundling: 'event.json'
Bundling: 'service.pyc'
Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com
Creating your new Lambda function
Starting new HTTPS connection (1): sts.amazonaws.com
Creating lambda function with name: testing
Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com
```
When trying to invoke on AWS, 
```
START RequestId: 976934e4-9039-11e8-b83f-d7c0f6a17314 Version: $LATEST
Unable to import module 'service': No module named 'OpenSSL'
```
I've noticed that my deployment zip doesn't have OpenSSL installed either.
Pretty sure I am missing something, just can't say what.

Thanks in advance,
Razvan

**Comment by kmbenitez** [comment]
I'm not sure why deploying with no requirements file didn't upload the right directories. I was able to move a step further by creating a requirements.txt file and then deploying using `lambda deploy --requirements='requirements.txt'`

Depending on your machine, you may (likely will) need to make sure that you compile this package against a Linux system. I like the method here: https://medium.freecodecamp.org/escaping-lambda-function-hell-using-docker-40b187ec1e48

**Comment by RazvanTolbaru** [comment]
@kmbenitez, thank you for the reply. 
I am using the package to create the scaffolding for the lambda function and I upload afterwards the deployment package (easier this way to add all the subnets and security groups in one go)

Yes, I build my deployment package on a Linux host.

**Comment by RazvanTolbaru** [comment]
Closing down. building the deployment package manually
