### ISSUE TITLE
Error with lambda invoke

### ISSUE THREAD

**Issue by maxpearl** [nficano/python-lambda#138]
running lamdba invoke throws this error: 
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
Steps to replicate:
- create pipenv
- pipenv install python-lambda
- create event.json
- edit yaml file
- create python service.py
- run lambda invoke -v

It's not fatal, the service runs fine.

**Comment by w00kie** [comment]
This is fixed in Pull Request #140 but it's been sitting there since early may without a merge or a release.

**Comment by aluciffer** [comment]
I have the same problem please pull!

**Comment by kon** [comment]
+1

**Comment by rishabh-bhargava** [comment]
#140 is now merged and the latest code is released to PyPI. Closing the issue.
