### ISSUE TITLE
README supplement

### ISSUE THREAD

**Issue by maxtortime** [nficano/python-lambda#19]
Thanks for this project and I followed the README very easily, but I think README needs some supplement for new users of AWS (like me).

While I was following that README, Before running of `lambda deploy`, I should create IAM users for getting `aws_access_key_id` and `aws_secret_access_key`. Nextly, I should create `~/.aws/credentials` files for saving both key or just input to `config.yaml` (don't need to share). Finally, I should attach two policies to my IAM users, `AWSLambdaFullAccess` (for creating lambda function) and `IAMFullAccess` (perfoming `iam:getUser`). (I think Amazon provides more narrow polices) 

Summary,
Before run `lambda deploy`
1. Create IAM users
2. Get `aws_access_key_id` and `aws_secret_access_key`
3. Save above keys to `~/.aws/credentials`
4. Attach `AWSLambdaFullAccess` and `IAMFullAccess`
5. Run `lambda deploy`

Regards

**Comment by superstrong** [comment]
In addition to creating a new user, I needed to create a new role specifically called `lambda_basic_execution` with the appropriate policies.

**Comment by maxtortime** [comment]
I think making user at AWS IAP console (web browser) is easy, so just writing instruction to documentation will be better. May I edit README?

**Comment by lukemalcolm** [comment]
Please can I second the addition of README steps around:
IAM Policies needed for the developers account
IAM Role called `lambda_basic_execution `needed with the `LambdaBasicExecution `policy attached.

Tx.

**Comment by nelsonSchwarz** [comment]
I also spent unnecessary time working to figure out this policy issue. Please add to README.

**Comment by nficano** [comment]
will do asap
