### ISSUE TITLE
S3 Support

### ISSUE THREAD

**Issue by sebastianmacias** [nficano/python-lambda#23]
I'm getting an error when trying to deploy:

`botocore.exceptions.ClientError: An error occurred (RequestEntityTooLargeException) when calling the UpdateFunctionCode operation: Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation`

It could be avoided by uploading the lambda function code first to S3 and then deploying it to lambda from there.

Do you plan to support this?

Tnx

**Comment by jmeekhof** [comment]
It's worth considering...

**Comment by kilna** [comment]
My build + deploy process needs to go through S3 as well, this would be super useful

**Comment by slapula** [comment]
Wow, totally missed this issue. @kilna I'm working on deploying to S3.  Hopefully, it will be ready in a couple weeks.

**Comment by nficano** [comment]
released!

**Comment by slapula** [comment]
I have an S3 deployment PR ready to submit (which should directly satisfy the requestor's need here).  Expect to see it on Oct 1st.
