### ISSUE TITLE
AWS Credentials from Environmental Variables

### ISSUE THREAD

**Issue by tdhopper** [nficano/python-lambda#27]
Great project, @nficano.

Have you considered allowing AWS credentials to be defined from environmental variables? 

My use case is automating a deploy from Travis. This is the easiest solution I can think of.

**Comment by idwsjnc** [comment]
tdhopper, the way the boto3 lib is invoked, if you don't specify the keys in the config file, it will try to use other credential methods:

http://boto3.readthedocs.io/en/latest/guide/configuration.html

**Comment by tdhopper** [comment]
@idwsjnc: Awesome. Thanks.
