### ISSUE TITLE
Client Role Error

### ISSUE THREAD

**Issue by barnabygordon** [nficano/python-lambda#28]
Hi,

After building a simple function and running `lambda deploy` I receive this error:

`botocore.exceptions.ClientError: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.`

Has anyone else had this issue? Is there a config file somewhere specifying the role that I can edit?

**Comment by nficano** [comment]
Ah yes, I need to update the README but haven't had the time. Please refer to this similar issue that includes the instructions for fixing this: https://github.com/nficano/python-lambda/issues/19

**Comment by grandearminho** [comment]
@nficano I've trying following the steps specified by maxtortime, but I still get the same exception. I also tried the steps specified by superstrong (although I'm not sure I did those correctly), but to no avail. Would it be possible to get more specific steps and an explanation of what permissions are being given for what reason?

Thanks!

**Comment by nricklin** [comment]
in the config.yaml file I had to set the role name to be:
```service-role/<the-name-of-your-role>```
