### ISSUE TITLE
Deploy only packages necessary for your code

### ISSUE THREAD

**Issue by mdorn** [nficano/python-lambda#29]
Great project @nficano, thanks for making it.

I noticed that `lambda deploy` zips up and deploys **all** the packages in the virtualenv, including ones that are only needed to run python-lambda itself locally (e.g. boto, pip, pyaml, etc.) and therefore unneeded on AWS.  It would be nice to be able to restrict this, maybe an additional config variable where you can indicate package names needed for your code?

**Comment by gferon** [comment]
I agree as well! Probably using a requirements.txt file to list the dependencies to deploy would be a good approach (it's also standard). I can make a PR is this is interesting for you guys.

**Comment by nficano** [comment]
@gferon that would be insanely appreciated!

**Comment by nficano** [comment]
all done!
