### ISSUE TITLE
Import of local modules from the main module doesn't work when invoking 

### ISSUE THREAD

**Issue by Ghopper21** [nficano/python-lambda#31]
I have a lambda that imports a local module (i.e. another Python file in the same folder as the main lambda module, as opposed to a pip installed package). Doing a `lambda deploy` works, and the resulting lambda on AWS works also. However, when I do `lambda invoke` for local testing, I get an `ImportError: No module named foo` where `foo` is the module I'm trying to import.

**Comment by kadrach** [comment]
As a workaround, you can set (or append) your `PYTHONPATH`, e.g. `PYTHONPATH=$(pwd) lambda invoke` should work.

**Comment by jmeekhof** [comment]
The code to allow this to work has been merged into master. It'll be available next release.
