### ISSUE TITLE
Local Test - Modify service.py file did not reflect the changes

### ISSUE THREAD

**Issue by demonxy468** [nficano/python-lambda#32]
I am new to lambda and Bash script.  When I modify the service.py under the root folder, e.g. change **e + pi** to **e - pi**, it did not return the result after the changes.  Anyone could help? Or do I need to recompiled the service.pyc file everytime I make the changes?  

Thanks for the help.

**Comment by nficano** [comment]
Can you confirm returning other things work? such as a simple string or a small fibonacci sequence?

**Comment by demonxy468** [comment]
Hi @nficano ,

The modified code is not reflect my changes even I change the return type:
```
`# -*- coding: utf-8 -*-
def handler(event, context):
    e = event.get('e')
    pi = event.get('pi')
    return 'working'`
```
Even I changed the return value, it still returned us 5.858.
I am running this lab at Windows via "Bash on Ubuntu" application. Will it make any differences?

**Comment by nficano** [comment]
and you're calling ``lambda deploy`` after you modify your code?

**Comment by demonxy468** [comment]
Sorry for not adding that much detail.  After modifying service.py, I ran `lambda invoke -v` , it returned the result before changing. Then I tried to recompile the python-lambda script to service.pyc to invoke again, by running `python -m compileall service.py`, didn't work either.  But the result will change if I changed event.json file.

**Comment by demonxy468** [comment]
Still not sure if it is the Ubuntu on Windows platform causes the error. I switched to AWS EC2 Ubuntu environment, the issue was fixed.
