### ISSUE TITLE
deployment fails

### ISSUE THREAD

**Issue by shaddu** [nficano/python-lambda#37]
gettiing below error while deploying the function

botocore.exceptions.ClientError: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defi
ned for the function cannot be assumed by Lambda.

deployment fails after this message 
Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com
Creating your new Lambda function
Starting new HTTPS connection (1): sts.amazonaws.com
Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com

**Comment by notexistence** [comment]
I have the same problem. Is there any way to work around this?

**Comment by shaddu** [comment]
for me it worked when i added a new AWS IAM role = 'lambda_basic_execution' with lambda execution rights

**Comment by jmeekhof** [comment]
@shaddu Can you elaborate on this a bit? I've created a role, but how do we tell our deployer which role to use?

**Comment by shaddu** [comment]
@jmeekhof basically that role is expected in python-lambda execution. So if u manually create it and then use lambda deploy. It should work
