### ISSUE TITLE
Function already exists error after initial lambda deploy

### ISSUE THREAD

**Issue by zachdb86** [nficano/python-lambda#38]
Hi,

My deployment completes successfully the first time, but errors out on subsequent deployments with this error:

`botocore.exceptions.ClientError: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: es_get_channel_http_microservice`

**Comment by movefast** [comment]
Haven't run into this issue myself but looking at the code it only creates a function if you give a new name in the config, maybe give another try after pulling in the latest changes and reinstall botocore/boto3; if still doesn't work, you can try to change the script default to updating the function at aws_lambda/aws_lambda.py#L86 and see if you are still getting the same exception.

**Comment by geekmuse** [comment]
+1 Seeing this same behavior.

**Comment by asaolabs** [comment]
Believe this is addressed with the latest merged changes.  The client.list_functions() call to AWS returns paged results.  We now query for the "complete list" before checking to see if the function exists or not.  You were likely to start running into this if you had over 50 Lambda functions defined.

**Comment by nficano** [comment]
Thanks sir! will close
