### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by phuong-mai-mai** [nficano/python-lambda#485]
Hey,
We would like to use the command `lambda build --requirements` with the newest python-lambda version which requires the following modules

- click
- boto3
- PyYAML

In version 3.2.6 of python-lambda the modules downloaded as dependencies which is not the case with the upgrade of python-lambda to 11.6.1. 

Environment: python 3.6

Can you please help us?
Thanks :)

**Comment by naimmalek** [comment]
Yes I'm having same issue.

python-lambda = 11.6.1
python = 3.8

**Comment by TheDen** [comment]
Experiencing this issue to. Can confirm the last version that correctly installs the dependencies is `10.0.4`

Looks like the changes in this https://github.com/nficano/python-lambda/commit/30a74e746a4500e66d56f80d0ef855fe4f73e562 broke the install requirements

**Comment by rishabh-bhargava** [comment]
@phuong-mai-mai just fixed this in #488 and released to PyPI in version 11.7.1.

**Comment by phuong-mai-mai** [comment]
Thank you 👍
