### ISSUE TITLE
Deploying Lambda removes VPC Configuration

### ISSUE THREAD

**Issue by zacharyabresch** [nficano/python-lambda#511]
I've been using your library for some time but am starting to run into some serious limitations. Today I added VPC configuration to my Lambda function through the AWS console because I discovered it needed this. I deployed using this package and it _removed_ the entire VPC configuration!!

I'm not really sure _why_ but it's a _major_ issue for me. I can't find anyway in the documentation to specify VPC configuration details with `lambda deploy` so I've now got to replace this tool for something that won't break my infrastructure. Puts me way behind schedule which is frustrating, but not your problem!

Anyway, wanted to let you know about the issue and see if you had any workarounds. Hope to hear from you soon!

**Comment by zacharyabresch** [comment]
Hello? Anyone? I know this is open-source but even a post saying "Sorry, too busy to work on this" would be nice. Or open it up for contributors.

**Comment by brxck** [comment]
Yes, it would be nice, but please understand that no one is obligated to help you. Maintainers have lives and other priorities. On the other hand, the information is [out there for you to find](https://github.com/nficano/python-lambda/issues/78).

**Comment by zacharyabresch** [comment]
Well aware of how open-source works but somehow we've both found time to reply to this thread. You link _was_ helpful so thank you for that. I went ahead and rewrote most of what I was using this tool for myself so no harm, no foul. Have a great day and stay safe!
