### ISSUE TITLE
Unable to import sub-directory module in AWS (but worked locally)

### ISSUE THREAD

**Issue by kwanster** [nficano/python-lambda#57]
I extended my python code to include a main lambda handler file and a module in a subdirectory:
- main lambda handler: **service.py**
- newly created module: **utils/slotutils.py** where it contains the **get_slot()** and **elicit_slot()** functions.

- In **service.py**, **get_slot()** and **elicit_slot()** were imported and referenced
- I was able to run the code locally with the command "lambda invoke -v"
- However, when the package was uploaded to AWS Lambda, executing the same python code resulted the following error message:
"Unable to import module 'service': No module named **utils.slotutils**"

Is there an extra setting needed to tell AWS to search for my newly created sub-directory "utils"?
Note: when I moved **slotutils.py** one directory to co-locate with **service.py**, my AWS Lambda worked fine. Thank you so much for sharing this great tool.

**Comment by kwanster** [comment]
I also just learned that the directory "utils" was not included in the zip package. I think I can make the problem go away if I can zip every newly defined directories in my virtual environment.

**Comment by jmeekhof** [comment]
@kwanster by default only the packages in your virtual environment and the files in your local directory are included in the zip. Your solution of placing your code in the same directory is a good solution. If, however you `utils` is generic and you want to use them elsewhere, you may want to create a pip style package. Then you'd be able to include them using the `--local-package` option.

**Comment by kwanster** [comment]
Thank you. I am closing the issue as there is nothing to be fixed.
