### ISSUE TITLE
Not pip installing a local package

### ISSUE THREAD

**Issue by tywoodpav** [nficano/python-lambda#58]
I am deploying `psycopg2` with my lambda build. Because `psycopg2` relies on the statically linked `libpq.so` library, `pip install` doesn't work (so neither does `--local-package`).

What I've done in the past is to pre-compile the psycopg2 package and copy the folder directly to lambda dist (no pip install). Seems like a useful feature.

https://github.com/jkehler/awslambda-psycopg2

**Comment by jmeekhof** [comment]
The solution to this is the same as the solution to #60.  Basically you need to do a `lambda build` and then use some sort of zip utility to add your `so`.
