### ISSUE TITLE
lambda function gets enviroment variable name

### ISSUE THREAD

**Issue by agustin320** [nficano/python-lambda#75]
When calling invoke, if you try to get a env var (`os.environ['host']`) set in the config file like so:
`host: $HOST` it will print out `$HOST` instead of the actual value of the envar $HOST

**Comment by bob-codingdutchmen** [comment]
Note: the README indicates the correct usage is `${HOST}`, but the result is the same for me: it just gets the name of the var

**Comment by bob-codingdutchmen** [comment]
I scrolled through the code, and it looks like the `get_environment_variable_value` function is only called when actually creating or updating a function on AWS lambda. It shouldn't be too hard to make a pull request for, but I'm not sure if I'll have the time soon.

**Comment by rishabh-bhargava** [comment]
Looks like this is solved with #87. Closing the issue.
