### ISSUE TITLE
Lambda Deploy command sets Lambda function's network to "No VPC"

### ISSUE THREAD

**Issue by rjaus** [nficano/python-lambda#78]
I'm not sure if this is a bug in the library, or how I've setup AWS / Lambda.

But everytime I run "lambda deploy" the lambda function I'm deploying to is set to "No VPC", dropping the subnets and security group.

Any ideas why this might be happening?

**Comment by bob-codingdutchmen** [comment]
Looking at [this code](https://github.com/nficano/python-lambda/blob/master/aws_lambda/aws_lambda.py#L575), you should enter the VPC settings in your config file. From your question it isn't clear wether you did, but make sure you have entered the `subnet_ids` and `security_group_ids` correctly

**Comment by gmyers-amfam** [comment]
I just created a [pull request](https://github.com/nficano/python-lambda/pull/116) to address this issue. In my PR I added a `--preserve-vpc` command line flag that allows you to not worry about setting the VPC info in the config.yaml

**Comment by shanmugavelsubramani** [comment]
Whats the status of this request? Is there a way i can include this fix into the package?
