### ISSUE TITLE
Ability to pass path (relative/absolute) of requirements file

### ISSUE THREAD

**Issue by karthich** [nficano/python-lambda#86]
My current usage of python-lambda uses a common requirements.txt file for all my lambda functions. Instead of placing the requirements.txt file in the function directory. Can I just add the ability to pass my own requirements.txt file instead of being forced to put the requirements.txt file in the function directory.

**Comment by karthich** [comment]
For context, this is my project structure:
`
-LambdaFunctionFolder1
  -service.py
  -requirements.txt
  -config.yaml
-LambdaFunctionFolder2
  -service.py
  -requirements.txt
  -config.yaml
`
Instead of that I would like to make the project look like this:
`
-Functions
	-LambdaFunctionFolder1
	  -service.py	  
	  -config.yaml
	-LambdaFunctionFolder2
	  -service.py
	  -config.yaml
  -requirements.txt
`

I am looking at the code and it looks like it should be an easy fix. I can work on this if this is something you guys want added to project.

**Comment by javamonkey79** [comment]
@karthich yes, please submit a PR

**Comment by scotwk** [comment]
@karthich - any work on this?  I want something similar.  I can submit a PR but I don't want to step on your toes if you have something in progress.

What will the interface look like?  afaict the click library doesn't support a parameter with an optional argument, so will `--use-requirements` be changed to be `--requirements PATH`?  That will break backwards compatibility, but other than that seems to be the right change.

**Comment by karthich** [comment]
Yes. Will submit a PR this weekend. Sorry been super busy at work.

**Comment by scotwk** [comment]
@karthich - I ended up making the changes locally to get stuff going on my end.  If you haven't started on it, I'm happy to submit mine.  Just let me know.

**Comment by karthich** [comment]
If you've already done it locally, I don't want to duplicate your work. Go ahead and submit yours. Thanks!
