### ISSUE TITLE
locally installed packages fail to deploy

### ISSUE THREAD

**Issue by javamonkey79** [nficano/python-lambda#92]
I have a locally install package, built like so:

`pip install . --upgrade`

I check disk, and its there in the virtualenv. 

However, when I run `lambda build` I get:

```
  Could not find a version that satisfies the requirement apt-commons==1.0 (from versions: )
No matching distribution found for apt-commons==1.0
```

I've tried the local-package argument, and it works, but then the module is not picked up in intellij, so, I'd prefer to just have it picked up from virtualenv.

**Comment by javamonkey79** [comment]
I've traced this down to this point:

` pip.main(['install', package, '-t', path, '--ignore-installed'])`

So, by the looks of it, it seems we have to use the `--local-package` option, however, this presents other challenges (package is not on path this way). 

Perhaps there is a way, by providing this in the requirements file?

**Comment by rbatta** [comment]
Did you find a way around this?

**Comment by javamonkey79** [comment]
@rbatta sorta... we were able to get it to work by just using `--local-package `. It has limitations, but, I think it has more to do with pip than python-lambda. Depending on your setup, it could be easier to just setup your own pypi.
